// 导入Metadata类型，Next.js中用于定义页面元数据如标题、描述等
import type { Metadata } from "next";

// 导入Inter字体样式，来自于Google Fonts，设置子集为latin以支持大部分拉丁字符
import { Inter } from "next/font/google";

// 引入全局CSS文件
import "./globals.css";

// 初始化Inter字体，指定子集为latin
const inter = Inter({ subsets: ["latin"] });

// 定义页面元数据对象，包含标题和描述信息
export const metadata: Metadata = {
  title: "Create Next App", // 页面标题
  description: "Generated by create next app", // 页面描述
};

// RootLayout组件，作为应用的根布局
export default function RootLayout({
  children, // 接收并渲染传入的子组件
}: Readonly<{ // 使用Readonly确保传递给组件的props不可变
  children: React.ReactNode; // children是React节点，可以是任何元素或组件
}>) {
  // 渲染HTML结构，其中lang属性设定为英语
  return (
    <html lang="en">
      {/* 将Inter字体应用于body，并渲染子组件内容 */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}